import jsPDF from 'jspdf';
import { WeeklySchedule, SkinType, WeeklyGraph } from '@/types/skincare';
import { weeklyGraphs } from '@/data/weeklyGraphData';

export function exportToPDF(schedule: WeeklySchedule, skinType: SkinType): void {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Jadwal Skincare Mingguan', 20, 20);
  
  doc.setFontSize(14);
  doc.text(`Tipe Kulit: ${getSkinTypeLabel(skinType)}`, 20, 30);
  
  let yPosition = 50;
  const days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];
  
  days.forEach(day => {
    const daySchedule = schedule[day];
    
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.setFontSize(16);
    doc.text(day, 20, yPosition);
    yPosition += 10;
    
    // Morning routine
    doc.setFontSize(12);
    doc.text('Pagi:', 25, yPosition);
    yPosition += 7;
    
    doc.setFontSize(10);
    daySchedule.morning.forEach((product, index) => {
      doc.text(`${index + 1}. ${product}`, 30, yPosition);
      yPosition += 5;
    });
    
    yPosition += 5;
    
    // Evening routine
    doc.setFontSize(12);
    doc.text('Malam:', 25, yPosition);
    yPosition += 7;
    
    doc.setFontSize(10);
    daySchedule.evening.forEach((product, index) => {
      doc.text(`${index + 1}. ${product}`, 30, yPosition);
      yPosition += 5;
    });
    
    yPosition += 10;
  });
  
  // Add footer
  doc.setFontSize(8);
  doc.text('Generated by Skincare Scheduler App', 20, 280);
  doc.text(new Date().toLocaleDateString(), 20, 285);
  
  // Save the PDF
  doc.save(`skincare-schedule-${skinType}-${new Date().toISOString().split('T')[0]}.pdf`);
}

export function exportWeeklyGraphToPDF(weeklyGraph: WeeklyGraph): void {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Weekly Skincare Schedule Graph', 20, 20);
  
  doc.setFontSize(14);
  doc.text(`Skin Type: ${getSkinTypeLabel(weeklyGraph.skinType)}`, 20, 30);
  doc.text(`Chromatic Number: ${weeklyGraph.chromaticNumber}`, 20, 38);
  doc.text(`Computation Time: ${weeklyGraph.computationTime}`, 20, 46);
  
  let yPosition = 60;
  
  // Group nodes by day
  const nodesByDay = weeklyGraph.nodes.reduce((acc, node) => {
    if (!acc[node.day]) acc[node.day] = [];
    acc[node.day].push(node);
    return acc;
  }, {} as Record<string, typeof weeklyGraph.nodes>);
  
  const dayNames = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
  const displayDayNames = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];
  
  dayNames.forEach((day, index) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    const dayNodes = nodesByDay[day] || [];
    if (dayNodes.length === 0) return;
    
    doc.setFontSize(16);
    doc.text(displayDayNames[index], 20, yPosition);
    yPosition += 8;
    
    dayNodes.forEach((node) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(12);
      const timeSlot = node.timeSlot === 'morning' ? 'Pagi' : 'Malam';
      const colorInfo = `Slot ${node.colorGroup}`;
      
      doc.text(`  ${timeSlot}: ${node.name} (${colorInfo})`, 25, yPosition);
      yPosition += 6;
    });
    
    yPosition += 5;
  });
  
  // Add summary statistics
  if (yPosition > 230) {
    doc.addPage();
    yPosition = 20;
  }
  
  doc.setFontSize(14);
  doc.text('Summary Statistics', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.text(`Total Products: ${weeklyGraph.nodes.length}`, 20, yPosition);
  yPosition += 6;
  doc.text(`Total Connections: ${weeklyGraph.edges.length}`, 20, yPosition);
  yPosition += 6;
  doc.text(`Conflict Connections: ${weeklyGraph.edges.filter(e => e.relation === 'conflict').length}`, 20, yPosition);
  yPosition += 6;
  doc.text(`Same-day Connections: ${weeklyGraph.edges.filter(e => e.relation === 'same-day').length}`, 20, yPosition);
  yPosition += 6;
  doc.text(`Adjacent-day Connections: ${weeklyGraph.edges.filter(e => e.relation === 'adjacent-day').length}`, 20, yPosition);
  
  // Add footer
  doc.setFontSize(8);
  doc.text('Generated by Skincare Scheduler App - Weekly Graph Visualization', 20, 280);
  doc.text(new Date().toLocaleDateString(), 20, 285);
  
  // Save the PDF
  doc.save(`weekly-skincare-graph-${weeklyGraph.skinType}-${new Date().toISOString().split('T')[0]}.pdf`);
}

function getSkinTypeLabel(skinType: SkinType): string {
  switch (skinType) {
    case 'normal': return 'Normal';
    case 'oily': return 'Berminyak';
    case 'dry': return 'Kering';
    case 'sensitive': return 'Sensitif';
    case 'combination': return 'Kombinasi';
    default: return skinType;
  }
}

export function exportToCalendar(schedule: WeeklySchedule, skinType: SkinType): void {
  const days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];
  const dayMap: { [key: string]: number } = {
    'Senin': 1,
    'Selasa': 2,
    'Rabu': 3,
    'Kamis': 4,
    'Jumat': 5,
    'Sabtu': 6,
    'Minggu': 0
  };

  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Skincare Scheduler//Skincare Schedule//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH'
  ];

  const startDate = new Date();
  const currentDay = startDate.getDay();
  const mondayOffset = currentDay === 0 ? -6 : 1 - currentDay;
  startDate.setDate(startDate.getDate() + mondayOffset);

  days.forEach((day, dayIndex) => {
    const currentDate = new Date(startDate);
    currentDate.setDate(startDate.getDate() + dayIndex);
    
    const daySchedule = schedule[day];
    
    // Morning routine
    const morningDate = new Date(currentDate);
    morningDate.setHours(8, 0, 0, 0);
    
    const morningSummary = `Skincare Pagi - ${getSkinTypeLabel(skinType)}`;
    const morningDescription = daySchedule.morning.map((product, index) => 
      `${index + 1}. ${product}`
    ).join('\\n');
    
    icsContent.push(createCalendarEvent(
      morningDate,
      morningSummary,
      morningDescription,
      30 // 30 minutes duration
    ));

    // Evening routine
    const eveningDate = new Date(currentDate);
    eveningDate.setHours(20, 0, 0, 0);
    
    const eveningSummary = `Skincare Malam - ${getSkinTypeLabel(skinType)}`;
    const eveningDescription = daySchedule.evening.map((product, index) => 
      `${index + 1}. ${product}`
    ).join('\\n');
    
    icsContent.push(createCalendarEvent(
      eveningDate,
      eveningSummary,
      eveningDescription,
      30 // 30 minutes duration
    ));
  });

  icsContent.push('END:VCALENDAR');

  // Create and download the file
  const blob = new Blob([icsContent.join('\r\n')], { type: 'text/calendar' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `skincare-schedule-${skinType}-${new Date().toISOString().split('T')[0]}.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function createCalendarEvent(
  date: Date,
  summary: string,
  description: string,
  durationMinutes: number
): string {
  const formatDate = (d: Date): string => {
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    const hours = String(d.getHours()).padStart(2, '0');
    const minutes = String(d.getMinutes()).padStart(2, '0');
    const seconds = String(d.getSeconds()).padStart(2, '0');
    
    return `${year}${month}${day}T${hours}${minutes}${seconds}`;
  };

  const startDate = formatDate(date);
  const endDate = formatDate(new Date(date.getTime() + durationMinutes * 60000));
  const uid = `${startDate}-${summary}@skincare-scheduler.com`;

  return [
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTART:${startDate}`,
    `DTEND:${endDate}`,
    `SUMMARY:${summary}`,
    `DESCRIPTION:${description}`,
    'STATUS:CONFIRMED',
    'SEQUENCE:0',
    'END:VEVENT'
  ].join('\r\n');
}

export function printSchedule(schedule: WeeklySchedule, skinType: SkinType): void {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];
  
  let htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Jadwal Skincare - ${getSkinTypeLabel(skinType)}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        h2 { color: #666; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
        .routine { margin-bottom: 20px; }
        .time-slot { font-weight: bold; color: #444; }
        .product { margin-left: 20px; margin: 5px 0; }
        .footer { margin-top: 30px; font-size: 12px; color: #888; }
        @media print {
          body { margin: 10px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <h1>Jadwal Skincare Mingguan</h1>
      <p><strong>Tipe Kulit:</strong> ${getSkinTypeLabel(skinType)}</p>
      <p><strong>Tanggal Cetak:</strong> ${new Date().toLocaleDateString('id-ID')}</p>
  `;

  days.forEach(day => {
    const daySchedule = schedule[day];
    htmlContent += `
      <div class="routine">
        <h2>${day}</h2>
        <div class="time-slot">🌅 Pagi:</div>
        ${daySchedule.morning.map((product, index) => 
          `<div class="product">${index + 1}. ${product}</div>`
        ).join('')}
        <div class="time-slot">🌙 Malam:</div>
        ${daySchedule.evening.map((product, index) => 
          `<div class="product">${index + 1}. ${product}</div>`
        ).join('')}
      </div>
    `;
  });

  htmlContent += `
      <div class="footer">
        <p>Generated by Skincare Scheduler App</p>
        <p>Catatan: Ikuti urutan aplikasi produk. Tunggu 2-3 menit antara produk untuk penyerapan optimal.</p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.print();
}